import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteHeader from "@/components/SiteHeader";
import AuthRefreshBootstrap from "@/components/AuthRefreshBootstrap";


export const metadata: Metadata = {
  title: "Globex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthRefreshBootstrap />
        <SiteHeader />
        {children}
      </body>
    </html>
  );
}
